Koverse/documentation

- docs/source/dev/webapp-record-converters.rst
- docs/source/devguide.rst
Record converters are used for downloading data set records
> KC-4738 Added docs for Web app record converters

- docs/source/api.yaml
- open-api/api.yaml
- open-api/paths/applicationId.yaml
- open-api/paths/applications.yaml
- open-api/schemas/apiClient.yaml
This should add the new applications endpoints to the docs.
> add applications endpoints

- docs/source/api.yaml
- open-api/api.yaml
- open-api/paths/dataSetAttributeNames.yaml
- open-api/paths/dataSetAttributes.yaml
- open-api/paths/dataSetClearDataSet.yaml
- open-api/paths/dataSetId.yaml
- open-api/paths/dataSetRecords.yaml
- open-api/paths/dataSetRepair.yaml
- open-api/paths/dataSets.yaml
- open-api/paths/records.yaml
https://koverse.atlassian.net/browse/KC-5916
Went through the sections that are meant to be used by web apps as specified in the ticket. I went through each one and wrote a quick test to try the happy path as well as an obvious error path. I then updated the docs accordingly.
I'm not used to the openapi stuff and may have updated that wrong. I tried to make sure the information matched the docs in source/api.yaml. I can't build this on my own machine so I don't know if there were errors. I did get a copy of it built so I could look through and make sure everything seemed correct.
Tickets have been generated for the 500 Server Error responses but that has been left in the docs since it's the current response.
> Kc 5916 update rest docs for 3.0 webapps

- docs/source/api.yaml
- docs/source/readthedocs.yml
- open-api/api.yaml
- open-api/paths/dataSetAttributeNames.yaml
- open-api/paths/dataSetAttributes.yaml
- open-api/paths/dataSetClearDataSet.yaml
- open-api/paths/dataSetId.yaml
- open-api/paths/dataSetRecords.yaml
- open-api/paths/dataSetRepair.yaml
- open-api/paths/dataSets.yaml
- open-api/paths/records.yaml
REST API changes from KC-5916 https://koverse.atlassian.net/browse/KC-5916
> Kc 5956 mering 3.0 rest api changes into 3.1

- docs/source/releasenotes/2.11.rst
> Kc 5970 2.11.2 release

- docs/source/releasenotes/3.2.rst
> Kc 5970 3.2.0 release

- docs/source/dev/analytics/pyspark_transform.rst
Changed pyspark transform documentation to match koverse-examples
> Kc 5892 fix python test doc

- docs/source/releasenotes/2.11.rst
Release notes for 2.11.3
Only item I know of is the avro parser fix.
> KC-5990 Release notes update for 2.11.3

- docs/source/releasenotes/2.11.rst
- docs/source/releasenotes/3.1.rst
> Kc 5991 3.1.4 release

- docs/source/releasenotes/2.11.rst
- docs/source/releasenotes/3.1.rst
- docs/source/releasenotes/3.2.rst
> Kc 5992 3.2.1 release

- docs/source/releasenotes/3.2.rst
Adding the one bug fix I found that was in the most recent release.
> Added bug fix to release docs

- docs/source/releasenotes/3.2.rst
> Kc 6021 3.2.3 release

- docs/source/releasenotes/3.2.rst
> Kc 6052 3.2.4 release

- docs/source/admin/installguide.rst
- docs/source/releasenotes/3.2.rst
> 3.2.6 release notes

- docs/source/admin/buildbootstrapguide.rst
There were RST errors in the previous version of the Build + Bootstrap so fixing those
> Fixing restructured text errors

- docs/source/admin/runbook.rst
fingers-crossed for this to work
> scaling down images

- open-api/api.yaml
- open-api/paths/dataSetAttributeNames.yaml
- open-api/paths/dataSetAttributes.yaml
- open-api/paths/dataSetClearDataSet.yaml
- open-api/paths/dataSetId.yaml
- open-api/paths/dataSetIndexingPolicies.yaml
- open-api/paths/dataSetRecords.yaml
- open-api/paths/dataSetRepair.yaml
- open-api/paths/importFlowId.yaml
- open-api/paths/importFlowNormalizations.yaml
- open-api/paths/importFlowNormalizationsId.yaml
- open-api/paths/importScheduleId.yaml
- open-api/paths/queryObject.yaml
- open-api/paths/queryObjectNames.yaml
- open-api/paths/records.yaml
- open-api/paths/transformId.yaml
- open-api/paths/transforms.yaml
- open-api/schemas/badrequest.yaml
> Revert "Kc 5978 update rest api status codes"

- open-api/paths/dataSets.yaml
Corresponding PR to https://github.com/Koverse/Koverse/pull/2118
> KC-5845 - Add additional optional parameter to get datasets.

- open-api/api.yaml
- open-api/paths/searchAutocompleteField.yaml
Adding in search field options per KC 5707
> KC 5707 re document search endpoints

- docs/source/api.yaml
- docs/source/releasenotes/3.2.rst
- open-api/api.yaml
- open-api/paths/dataSetAttributeNames.yaml
- open-api/paths/dataSetAttributes.yaml
- open-api/paths/dataSetClearDataSet.yaml
- open-api/paths/dataSetId.yaml
- open-api/paths/dataSetIndexingPolicies.yaml
- open-api/paths/dataSetRecords.yaml
- open-api/paths/dataSetRecordsV2.yaml
- open-api/paths/dataSetRepair.yaml
- open-api/paths/importFlowId.yaml
- open-api/paths/importFlowNormalizations.yaml
- open-api/paths/importFlowNormalizationsId.yaml
- open-api/paths/importScheduleId.yaml
- open-api/paths/queryLuceneV2.yaml
- open-api/paths/queryObject.yaml
- open-api/paths/queryObjectNames.yaml
- open-api/paths/queryObjectNamesV2.yaml
- open-api/paths/queryObjectV2.yaml
- open-api/paths/records.yaml
- open-api/paths/transformId.yaml
- open-api/paths/transforms.yaml
- open-api/schemas/badrequest.yaml
> KC-6147 - Add v2 datasets and query endpoint.

- .gitignore
- docs/source/readthedocs.yml
<https://koverse.atlassian.net/browse/KC-0000>
CHANGEME
- CHANGEME
- CHANGEME
- CHANGEME
CHANGEME
> Merge main into 3.4 python version change

- docs/source/releasenotes/3.4.rst
<https://koverse.atlassian.net/browse/KC-6336>
3.4.1 release notes
- 3.4.rst
CHANGEME
> Kc 6336 3.4.1 release

- docs/source/releasenotes/3.4.rst
- docs/source/usage/addons.rst
- docs/source/usageguide.rst
<https://koverse.atlassian.net/browse/KC-6336>
3.4.1 release
Merged main in
- 3.4.rst
Tested locally
> Kc 6336 3.4.1

- docs/source/dev/analytics/pyspark_transform.rst
<https://koverse.atlassian.net/browse/KC-5884>
Updated documentation to reflect correct way to read input datasets
- pyspark_transform.rst
Updated to match koverse-examples. Tested subjectSentiment transform from examples locally
> Kc 5884 pyspark input dataset doc

- docs/source/releasenotes/3.9.rst
<https://koverse.atlassian.net/browse/KDP-65>
Release notes for 3.9.0 release.
Jira release pages: <https://koverse.atlassian.net/projects/KC/versions/19201/tab/release-report-all-issues>
and <https://koverse.atlassian.net/projects/KDP/versions/19202/tab/release-report-all-issues>
> KDP-65 release note for 3.9

- docs/source/releasenotes/3.9.rst
<https://koverse.atlassian.net/browse/KDP-179>
Updated release notes with 3.9.1 
- 3.9 release notes
Built and viewed index.html
> Added release notes for 3.9.1

- docs/source/releasenotes/3.9.rst
<https://koverse.atlassian.net/browse/KDP-556>
> KDP-556 There was an extra fix in the release that wasn't on my list

- docs/source/releasenotes/3.11.rst
We are releasing the keycloak changes as a feature release.
> Create 3.11 release notes
